### ISSUE TITLE
Can not enable Online Registration when CiviRules enabled.

### ISSUE THREAD

**Issue by dsuguy2007** [CiviCooP/org.civicoop.civirules#55]
Posted the following on StackExchange: http://civicrm.stackexchange.com/questions/8521/why-can-i-not-enable-online-registration-on-events/8563#8563

**Comment by jaapjansma** [comment]
Could you try with the latest CiviRules? Inspecting the code from the backtrace given in your stackexchange seem to mismatch the latest code. So it might be that this one is already fixed.

**Comment by dsuguy2007** [comment]
I just re-downloaded tagged version 1.2 and installed it. Get the same error. I had downloaded the master and was getting the error too.

**Comment by dsuguy2007** [comment]
After disabling civirules I get the following errors:


    Warning: Invalid argument supplied for foreach() in _emailapi_civix_civicrm_managed() (line 171 of /home/civicrm_extensions/org.civicoop.emailapi/emailapi.civix.php).
    Warning: Invalid argument supplied for foreach() in _pdfapi_civix_civicrm_managed() (line 176 of /home/civicrm_extensions/org.civicoop.pdfapi/pdfapi.civix.php).
    Notice: Undefined property: CRM_Civirules_BAO_Condition::$label in CRM_Civirules_BAO_Condition::add() (line 59 of /home/civicrm_extensions/org.civicoop.civirules/CRM/Civirules/BAO/Condition.php).

**Comment by jaapjansma** [comment]
@dsuguy2007 the warnings you get are similar to the one you reported on the sms api and the fix is similar too. Are you a developer? If so you could fix the warnings yourself by applying the same fix as in https://github.com/CiviCooP/org.civicoop.smsapi/commit/8d577a78c2c6c60bea0e741770e5fe1932d2d7cf

**Comment by dsuguy2007** [comment]
I am not a developer. Either way, it still doesn't explain why civiRules breaks Events ability to enable register online.

**Comment by dsuguy2007** [comment]
I did confirm that is happening on the demo version at http://dmaster.demo.civicrm.org   Go to Manage Events, configure any event, select Online registration tab and enable online registration. click Save and Done and you will get the id is not a valid integer error.

**Comment by jaapjansma** [comment]
@dsuguy2007 thanks for your comment. When we have funding we might look into this issue.

**Comment by jaapjansma** [comment]
@dsuguy2007 by the way I am running a 4.6.10 site with CiviRules and with Event registration and the event registration seems to work.

**Comment by dsuguy2007** [comment]
The fact that it's happening on the demo site shows that it's not just a fluke with my site. There's something wrong with the extension. Are you saying that just because your specific site isn't experiencing this issue that you don't care to fix the bug that is happening in at least 2 other sites?

**Comment by jaapjansma** [comment]
@dsuguy2007 I have only made an observation that CiviRules and Event registration is working on one site. Your point is clear that it is not working on your site and the demo site. Not sure why. 
And you are right to assume that when CiviRules wasn't working on a CiviCRM site I manage I would fix the bug. Yes then it was in my interest to fix it.

However the CiviRules is not our product. We have developed the CiviRules funded by two clients and the source code we share with the community. Last year we had some more funding from other clients to fix particular bugs and issues. In addition to this funded work we have also spent some free time in fixing bugs and testing whether the extension is 4.6 compatible. 

So when there is funding I am more than happy to fix this issue. Otherwise you might wait till another developer can fix this issue or you can ask another developer. We would love to see more developers.

**Comment by ErikHommel** [comment]
@dsuguy2007 for me you are crossing a border with your remark "Are you saying that just because your specific site isn't experiencing this issue that you don't care to fix the bug that is happening in at least 2 other sites?" We care enough to share our work with the community.

**Comment by shawnholt** [comment]
@dsuguy2007 if you are not a developer and can't fund the fix one suggestion is that you document as best you can the bug: specific case,error message,code,assumptions, etc so that someone else may resolve and others may avoid.  That would be a positive contribution.

**Comment by dsuguy2007** [comment]
I have documented all I know to document. If there is more information you need please tell me what it is you need and how to obtain it and I will provide it. My issue is with you saying that this extension is compatible with a version when it has a bug in it that prevents it from being used. First it broke schedule reminders and that was apparently fixed and now it breaks online registration for events. I have confirmed that it does this on my site, the 4.6 demo site, and the 4.7 demo site. That's 3 sites that get the exact same error.

Steps to reproduce:
1. Enable CiviRules.
2. Create a new Event or go to an existing one.
3. Go to the Online Registration tab and enable it if it is not enabled.
4. If you click save then it just sits there with the spinning civi logo, if you click save and done then it gives you the error message, "Sorry but we are not able to provide this at the moment.
id is not a valid integer". I provided the backtrace from my site with the error. 

I have tried the released version 1.2 and the most current master branch with the same effect.

**Comment by ErikHommel** [comment]
@dsguy2007 as stated before, we do NOT deliver (or sell) a product. We share our work. We will fix errors and bugs once we have funding, that is our way of working, and the only way in which we can share our work for free. We have not, and never will, test CiviRules with all the functionality that is possible with CiviCRM. We give you what we have done on our projects. Unfortunately your error does not happen on our projects, so we have no paying customer to fix your issue. If you can find a programmer that can fix it for free, there is documentation.

**Comment by shawnholt** [comment]
I can see there is a lot going on here but @dsuguy2007 this might answer you question on how to document what is happening: http://civicrm.stackexchange.com/questions/6399/how-do-i-debug-civicrm-when-i-hit-a-blank-page-white-screen-fatal-error/6400#6400
also http://wiki.civicrm.org/confluence/display/CRMDOC/Debugging+for+developers
(I'm just trying to make this more constructive but like @ErikHommel have no sites using this now so without funding ...)

**Comment by dsuguy2007** [comment]
Probably put the bug in so you could make money.

**Comment by PalanteJon** [comment]
@dsuguy2007 You may want to read this: http://jeremyckahn.github.io/blog/2014/10/19/open-source-does-not-mean-free-labor/

**Comment by jaapjansma** [comment]
Our client Werk met Zin had this same issue on their installation and they funded to fix this issue.
